name: My First CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ShellCheck
        run: shellcheck script.sh  # В Ubuntu на GitHub Actions он уже предустановлен

      - name: Run our shell script
        run: |
          chmod +x script.sh
          ./script.sh
